<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            [
                "id_user" => 1,
                "nip" => "12345678901",
                "nama_lengkap" => "Alfian",
                "tempat_lahir" => "Tangerang",
                "alamat" => "Jl. Free Fire Factory, No. 1, Kla Only",
                "tanggal_lahir" => "2001-02-25",
                "gender" => "L",
                "telepon" => "082334784621",
                "email" => "alfianganteng@gmail.com",
                "npwp" => "09.254.294.3-407.000",
                "id_golongan_pangkat" => 17,
                "id_eselon" => 3,
                "id_jabatan" => 1,
                "id_lokasi_kerja" => 1,
                "id_unit_kerja" => 1,
                "id_agama" => 1,
                "foto_profil" => null,
                "password" => Hash::make("password"),
                "role" => "superadmin",
                "created_at" => now(),
                "created_by" => "root",
            ],
            [
                "id_user" => 2,
                "nip" => "10987654321",
                "nama_lengkap" => "Regita",
                "tempat_lahir" => "Tangerang",
                "alamat" => "Jl. Free Fire Factory, No. 1, Kla Only",
                "tanggal_lahir" => "2001-10-25",
                "gender" => "P",
                "telepon" => "082362199784",
                "email" => "regita@gmail.com",
                "npwp" => null,
                "id_golongan_pangkat" => 16,
                "id_eselon" => 3,
                "id_jabatan" => 1,
                "id_lokasi_kerja" => 1,
                "id_unit_kerja" => 1,
                "id_agama" => 1,
                "foto_profil" => null,
                "password" => Hash::make("password"),
                "role" => "superadmin",
                "created_at" => now(),
                "created_by" => "root",
            ],
            [
                "id_user" => 3,
                "nip" => "54321109876",
                "nama_lengkap" => "Ahmad Saugi",
                "tempat_lahir" => "Jakarta",
                "alamat" => "Jl. Buah Melon, No. 22, Warna Merah",
                "tanggal_lahir" => "1999-05-29",
                "gender" => "L",
                "telepon" => "082378462134",
                "email" => "saugi@gmail.com",
                "npwp" => "09.251.294.3-407.000",
                "id_golongan_pangkat" => 2,
                "id_eselon" => 5,
                "id_jabatan" => 2,
                "id_lokasi_kerja" => 2,
                "id_unit_kerja" => 2,
                "id_agama" => 1,
                "foto_profil" => null,
                "password" => Hash::make("password"),
                "role" => "officer",
                "created_at" => now(),
                "created_by" => "root",
            ],
            [
                "id_user" => 4,
                "nip" => "18765432109",
                "nama_lengkap" => "Wahyu Amirulloh",
                "tempat_lahir" => "Bogor",
                "alamat" => "Jl. Kegelapan, No. 69, Warna Hitam",
                "tanggal_lahir" => "2002-03-22",
                "gender" => "L",
                "telepon" => "082378413462",
                "email" => "wahyu@gmail.com",
                "npwp" => null,
                "id_golongan_pangkat" => 3,
                "id_eselon" => 9,
                "id_jabatan" => 3,
                "id_lokasi_kerja" => 3,
                "id_unit_kerja" => 3,
                "id_agama" => 1,
                "foto_profil" => null,
                "password" => Hash::make("password"),
                "role" => "officer",
                "created_at" => now(),
                "created_by" => "root",
            ],
            [
                "id_user" => 5,
                "nip" => "18732109654",
                "nama_lengkap" => "Muhammad Fauzan",
                "tempat_lahir" => "Bandung",
                "alamat" => "Jl. Keterangan, No. 88, Warna Putih",
                "tanggal_lahir" => "2001-05-27",
                "gender" => "L",
                "telepon" => "082384134627",
                "email" => "fzn0x@gmail.com",
                "npwp" => "09.259.291.3-407.000",
                "id_golongan_pangkat" => 4,
                "id_eselon" => 6,
                "id_jabatan" => 4,
                "id_lokasi_kerja" => 4,
                "id_unit_kerja" => 4,
                "id_agama" => 1,
                "foto_profil" => null,
                "password" => Hash::make("password"),
                "role" => "officer",
                "created_at" => now(),
                "created_by" => "root",
            ],
            [
                "id_user" => 6,
                "nip" => "43187652109",
                "nama_lengkap" => "Moepoi",
                "tempat_lahir" => "Jakarta",
                "alamat" => "Jl. Isekai, No. 69, Warna Biru",
                "tanggal_lahir" => "2000-01-19",
                "gender" => "L",
                "telepon" => "082341346298",
                "email" => "moepoi.dev@gmail.com",
                "npwp" => "09.259.299.3-407.000",
                "id_golongan_pangkat" => 5,
                "id_eselon" => 7,
                "id_jabatan" => 5,
                "id_lokasi_kerja" => 5,
                "id_unit_kerja" => 5,
                "id_agama" => 4,
                "foto_profil" => null,
                "password" => Hash::make("password"),
                "role" => "officer",
                "created_at" => now(),
                "created_by" => "root",
            ],
            [
                "id_user" => 7,
                "nip" => "65210943187",
                "nama_lengkap" => "Nugraha",
                "tempat_lahir" => "Jakarta",
                "alamat" => "Jl. Buaya, No. 11, Warna Hijau",
                "tanggal_lahir" => "1995-01-19",
                "gender" => "L",
                "telepon" => "082413462983",
                "email" => "nugraha@gmail.com",
                "npwp" => "09.259.296.3-407.000",
                "id_golongan_pangkat" => 6,
                "id_eselon" => 8,
                "id_jabatan" => 6,
                "id_lokasi_kerja" => 6,
                "id_unit_kerja" => 6,
                "id_agama" => 1,
                "foto_profil" => null,
                "password" => Hash::make("password"),
                "role" => "officer",
                "created_at" => now(),
                "created_by" => "root",
            ],
        ]);
    }
}
